Version 4
SymbolType BLOCK
RECTANGLE Normal 96 65 -96 -64
WINDOW 3 0 0 Center 2
SYMATTR Value LowPass
SYMATTR Prefix X
SYMATTR ModelFile C:\Users\Acer\repos\ERG-2025\filter\SPICE-models\LowPass.CIR
PIN -96 -32 LEFT 8
PINATTR PinName IN
PINATTR SpiceOrder 1
PIN -96 32 LEFT 8
PINATTR PinName GND
PINATTR SpiceOrder 2
PIN 0 -64 TOP 8
PINATTR PinName V+
PINATTR SpiceOrder 3
PIN 0 64 BOTTOM 8
PINATTR PinName V-
PINATTR SpiceOrder 4
PIN 96 -32 RIGHT 8
PINATTR PinName OUT
PINATTR SpiceOrder 5
